import { assertAllowlistedImagePatch, materializeImagePatch } from "./patch";
import { assertAssetRef, assertImageBytes } from "./generate";
import type { ImagePatchPlan, ResearchImageDocument } from "./types";

export const RESEARCH_IMAGE_DOCUMENTS_QUERY = `*[_type == "research"]{
  _id,
  language,
  title,
  seoTitle,
  excerpt,
  topic,
  studyDesign,
  population,
  intervention,
  outcomes,
  mainFindings,
  practicalInterpretation,
  pmid,
  doi,
  translationSourceId,
  translationSlug,
  mainImage{
    alt,
    hotspot,
    crop,
    asset
  }
}`;

export type ResearchImageReadClient = {
  fetch: (query: string) => Promise<unknown>;
};

export type ResearchImagePatchClient = {
  patch: (id: string) => {
    set: (fields: Record<string, unknown>) => {
      commit: () => Promise<unknown>;
    };
  };
};

export type ResearchImageUploadClient = {
  assets: {
    upload: (
      kind: "image",
      body: Buffer,
      options: { filename: string; contentType: string },
    ) => Promise<{ _id?: string }>;
  };
};

export async function loadResearchImageDocuments(
  client: ResearchImageReadClient,
): Promise<ResearchImageDocument[]> {
  const rows = await client.fetch(RESEARCH_IMAGE_DOCUMENTS_QUERY);
  if (!Array.isArray(rows)) return [];
  return rows.flatMap((row) => {
    const document = parseResearchImageDocument(row);
    return document ? [document] : [];
  });
}

/**
 * Upload generated bytes once. The returned id is a Sanity asset `_ref`.
 * Temporary generator URLs are never stored.
 */
export async function uploadResearchImage(
  client: ResearchImageUploadClient,
  bytes: Buffer,
  filename: string,
): Promise<string> {
  assertImageBytes(bytes);
  const asset = await client.assets.upload("image", bytes, {
    filename,
    contentType: "image/png",
  });
  assertAssetRef(asset?._id);
  return asset._id.trim();
}

/**
 * Patch one existing Research document.
 * A draft id stays a draft. A published id is updated in place.
 * This function has no publish path and no document-create path.
 */
export async function patchResearchImage(
  client: ResearchImagePatchClient,
  id: string,
  fields: Record<string, unknown>,
): Promise<void> {
  assertPatchableResearchId(id);
  assertAllowlistedImagePatch(fields);
  await client.patch(id).set(fields).commit();
}

export function assertPatchableResearchId(id: string): "published" | "draft" {
  if (id.startsWith("drafts.")) return "draft";
  if (id.startsWith("versions.") || id.includes(".")) {
    throw new Error(
      `Refusing to patch "${id}". Image backfill only updates published Research documents and drafts.`,
    );
  }
  return "published";
}

export function fieldsForImagePatch(
  patch: ImagePatchPlan,
  asset: { ref: string; hotspot?: unknown; crop?: unknown },
): Record<string, unknown> {
  const fields = materializeImagePatch(patch, asset);
  assertAllowlistedImagePatch(fields);
  return fields;
}

export function researchImageFilename(studyKey: string): string {
  const safe = studyKey
    .replace(/[^A-Za-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return `research-cover-${safe || "study"}.png`;
}

export function parseResearchImageDocument(value: unknown): ResearchImageDocument | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const row = value as Record<string, unknown>;
  if (typeof row._id !== "string" || !row._id.trim()) return null;
  return {
    _id: row._id.trim(),
    language: optionalString(row.language),
    title: optionalString(row.title),
    seoTitle: optionalString(row.seoTitle),
    excerpt: optionalString(row.excerpt),
    topic: optionalString(row.topic),
    studyDesign: optionalString(row.studyDesign),
    population: optionalString(row.population),
    intervention: row.intervention,
    outcomes: optionalStringArray(row.outcomes),
    mainFindings: row.mainFindings,
    practicalInterpretation: row.practicalInterpretation,
    pmid: optionalString(row.pmid),
    doi: optionalString(row.doi),
    translationSourceId: optionalString(row.translationSourceId),
    translationSlug: optionalString(row.translationSlug),
    mainImage: parseMainImage(row.mainImage),
  };
}

function parseMainImage(value: unknown): ResearchImageDocument["mainImage"] {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const row = value as Record<string, unknown>;
  const asset = parseAsset(row.asset);
  return {
    _type: optionalString(row._type) ?? undefined,
    alt: optionalString(row.alt),
    hotspot: row.hotspot,
    crop: row.crop,
    asset,
  };
}

function parseAsset(value: unknown): { _ref?: string; _id?: string; _type?: string } | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const row = value as Record<string, unknown>;
  return {
    _ref: optionalString(row._ref) ?? undefined,
    _id: optionalString(row._id) ?? undefined,
    _type: optionalString(row._type) ?? undefined,
  };
}

function optionalString(value: unknown): string | null {
  return typeof value === "string" ? value : null;
}

function optionalStringArray(value: unknown): string[] | null {
  if (!Array.isArray(value)) return null;
  return value.filter((item): item is string => typeof item === "string");
}
